[phases.setup]
nixPkgs = ['nodejs', 'dotnet-sdk_6', 'openssl', 'cacert']
aptPkgs = ['libicu-dev']

[phases.install]
cmds = ['dotnet restore --runtime linux-x64']

[phases.build]
cmds = [
    'dotnet dev-certs https',
    'dotnet publish -c Release --runtime linux-x64 --self-contained true'
]

[start]
cmd = './Server/bin/Release/net6.0/linux-x64/publish/music-manager-starter.Server'

[phases.setup.env]
DOTNET_CLI_TELEMETRY_OPTOUT = "1"
ASPNETCORE_ENVIRONMENT = "Production"
