[phases.setup]
nixPkgs = ['dotnet-sdk']
aptPkgs = ['libicu-dev']

[phases.build]
cmds = [
    'dotnet restore --runtime linux-x64 /p:ContinuousIntegrationBuild=true',
    'dotnet publish -c Release --runtime linux-x64 --self-contained true /p:UseAppHost=true /p:TreatWarningsAsErrors=false'
]

[start]
cmd = './Server/bin/Release/net8.0/linux-x64/publish/music-manager-starter.Server'
